### ISSUE TITLE
Static product dimensions are used instead of dynamic ones which can be added to cart item.

### ISSUE THREAD

**Issue by mrpsiho** [shipperhq/woocommerce-shipperhq#1]
I would suggest adjusting 'populateAttributes' to get dimensions from cart items or add a filter where third-party plugins could hook in and provide their values for dimensions.

**Comment by wsajosh** [comment]
Hi there. I'm not 100% sure I understand what you're trying to do? Are you suggesting that the dimensions could be entered by the end user?

**Comment by mrpsiho** [comment]
I suggest adding a filter so other plugins could modify dimensions
dynamically.

Another good solution would be using methods such as 'get_width' on a cart
item object. Similarly to how you did with 'get_weight'. Instead of getting
dimensions from post meta.

On 6 Mar 2018 1:21 p.m., "Josh" <notifications@github.com> wrote:

Hi there. I'm not 100% sure I understand what you're trying to do? Are you
suggesting that the dimensions could be entered by the end user?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shipperhq/woocommerce-shipperhq/issues/1#issuecomment-370749983>,
or mute the thread

**Comment by wsajosh** [comment]
Thanks for the details! I've raised this request with our development team. We will update you here

**Comment by mrpsiho** [comment]
Maybe this is resolved in the recent version of the plugin?

**Comment by wsajosh** [comment]
Hi @mrpsiho 

We're not currently seeing any demand for this feature and so will not be adding support for it at this time. However, if you'd like to implement it and create a pull request I'd be happy to get the change added in for you.

**Comment by colourgraphics** [comment]
The reason this idea would be good is that on our website the customer can enter a custom size to order a print. This could be 3 meters wide x 1.5 meters deep. This way the size calculation can be carried over to calculated the shipping price.

**Comment by wsajosh** [comment]
@colourgraphics Thanks for the feedback. We're not seeing a demand for this feature from other clients right now, but if you're interested in us building this out we would be happy to put together a quote. Please drop us a email on our sales email address if this is an option you'd like to explore. Alternatively the code is open so your developers can edit it and submit it here to be included in our next update subject to approval.

**Comment by mt-gareth** [comment]
I too am having this issue. This should be as simple as providing a filter on $formattedItem on the Mapper.php file. I know there has to be many others that have woocommerce stores with products that allow customers to select sizes.

All that needs to be done is change line 285 of Mapper.php from/to:
`$formattedItems[] = $formattedItem;`
`$formattedItems[] = apply_filters('shipperhq_formatted_item', $formattedItem, $product);`
