### ISSUE TITLE
Undefined offset: 0 in /plugins/woo-shipperhq/includes/shipperhq/ShippingMethod.php on line 214

### ISSUE THREAD

**Issue by GoodGuyTaj** [shipperhq/woocommerce-shipperhq#2]
Hi,

I keep getting this Notice in query manager on cart/checkout page.

Undefined offset: 0 in ..../plugins/woo-shipperhq/includes/shipperhq/ShippingMethod.php on line 214

Offending code:

`if(!empty($cgDetail) && is_array($cgDetail[0])) {`

I modified it to the following:

`if(!empty($cgDetail) && is_null(array_key_first($cgDetail))) {`

This resolved the notice from Query Manager.

If this is a valid solution, can a pull request be made and modifications incorporated?

**Comment by wsajosh** [comment]
Hi @GoodGuyTaj Thanks for raising this issue. It was fixed in version 1.4.8. Please update to the latest version of the module.
