### ISSUE TITLE
Add WordPress filter to allow users to customize the product data before sent to ShipperHQ

### ISSUE THREAD

**Issue by mt-gareth** [shipperhq/woocommerce-shipperhq#3]
Many users have custom products allowing their customer to select the size of the product. This market is blocked from using ShipperHQ plugin because there is currently no filters or actions added to the plugin. To solve this it would be very simple, please edit line 285 of Mapper.php from/to:
`$formattedItems[] = $formattedItem;`
`$formattedItems[] = apply_filters('shipperhq_formatted_item', $formattedItem, $product);`

**Comment by PeterElkoShipperHQ** [comment]
Hi @mt-gareth,

Thank you for these details regarding custom products. We will look into this.

Have a great day!

**Comment by mt-gareth** [comment]
@PeterElkoShipperHQ Thank you so much, adding filters and actions are pretty straight forward changes that allow your customers to jump in and change details before they are sent off for shipping details. The more hooks you add in the better, but this one will be enough for most users. I think it will be a great addition to your plugin and widen your potential customer pool. If you have any questions just reach out, thank you again.

**Comment by mt-gareth** [comment]
@PeterElkoShipperHQ I see that this was implemented in the latest update 1.6.0, THANK YOU, this will allow us to do so much more with the plugin. Keep up the good work.
